#!/bin/bash

OP=$1

if [[ "$OP" = "detect" ]]; then
  while true; do
    echo "{\"branches\":{\"master\":\"noopnoopmasterbranch$RANDOM\"},\"tags\":{\"latest/hash\":\"noopnooptaghash$RANDOM\",\"latest/name\":\"noop$RANDOM\"}}" > /tmp/actor-base/output
    cat /tmp/actor-base/output
    sleep 100
  done
fi
if [[ "$OP" = "check" ]]; then
    sleep 30
    echo "{\"revisions\":[{\"registry\":\"reg\",\"resolved_revision\":\"nooprev$RANDOM\",\"exist\":\"False\"}]}" > /tmp/actor-base/output
    cat /tmp/actor-base/output
    exit 0
fi
if [[ "$OP" = "upload" ]]; then
    echo "{\"builds\":[{\"registry\":\"reg\",\"tag\":\"nooprev$RANDOM\",\"succeeded\":\"True\"}]}" > /tmp/actor-base/output
    cat /tmp/actor-base/output
    exit 0
  done
fi