on:
  push:
    branches:


name: CI

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: takutakahashi/oci-image-operator
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - run: |
          make test
      - run: |
          make -C actor/base test
      - run: |
          make -C actor/github test
      - run: |
          make -C actor/registryv2 test
